ARMGNU ?= arm-none-eabi

ASFLAGS =
CPPFLAGS =
CFLAGS  = -Wall -O0 
CFLAGS += -nostdlib -nostartfiles -ffreestanding
LDFLAGS = 
NAME=linking
.PHONY : all clean

.SUFFIXES : 
.SUFFIXES : .c .s .o .elf .bin .list

all : $(NAME).bin

clean :
	rm -f *.bin
	rm -f *.elf
	rm -f *.o
	rm -f *.list

$(NAME).elf: $(NAME).o cstart.o start.o
	$(ARMGNU)-ld $(LDFLAGS) -T memmap $^ -o $@
	$(ARMGNU)-objdump -D $@ > $*.elf.list

.s.o:
	$(ARMGNU)-as $(ASFLAGS) $< -o $@ 
	$(ARMGNU)-objdump -D $@ > $*.list

.c.o:
	$(ARMGNU)-gcc $(CPPFLAGS) $(CFLAGS) -c $< 
	$(ARMGNU)-objdump -D $@ > $*.list

.elf.bin:
	$(ARMGNU)-objcopy $< -O binary $@

